################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""
hosts.py - /etc/hosts assembly, ported from mergeHostsAndResolv.bash stage_hosts
(lines 147-201), addHost (host-entry half), and selectNewDatabaseHost.

The host SET in /etc/hosts is the union of:
  - the local identity line (mergeHostsAndResolv local_identity)
  - bringup-registered direct peers (daemon BRINGUP_HOSTS_REGISTER -> addHost):
    this is why BABox is present even though wg0 is dead and it was never walked
  - discovery-discovered peers (walk -> addHostAndPropogate -> addHost)
All land in the frognet_hosts sentinel; stage_hosts normalizes + sort -u them.

[HOSTS_FORMAT_V2] every /etc/hosts 10.x line is "<ip> FrogNetHost.<net>" or
"<ip> FrogNetAdmin.<net>"; the self FrogNetHost line additionally gets the bare
"FrogNetHost" alias. Bare short names are stripped.

The route-install half of addHost is intentionally omitted: discovery calls
addHostAndPropogate with ping_host="" so addHost's route block never fires
(PING_HOST empty/0.0.0.0 -> skipped). The /24 routes are owned by promote.
"""
from __future__ import annotations

HOSTS_HEADER = [
    "################################################",
    "# AUTO-GENERATED BY mergeHostsAndResolv.bash   #",
    "################################################",
    "127.0.0.1 localhost",
]

# [FROGNETHOST_IS_NOT_LOOPBACK_V1] The bare alias "FrogNetHost" is NOT on the
# 127.0.0.1 line any more.
#
# It used to read "127.0.0.1 localhost FrogNetHost", while further down the
# same file the self line carries the alias too:
#
#     127.0.0.1   localhost FrogNetHost          <- first match wins
#     10.160.160.1 FrogNetHost.Seattle6 FrogNetHost
#
# Anything resolving the bare name got 127.0.0.1, because the loopback line
# sorts first and every resolver takes the first match. A peer told to reach
# "FrogNetHost" then talked to itself instead of the machine that owns the
# name, and the failure is silent -- the connection succeeds, to the wrong box.
#
# The alias belongs on the line that has the real address. _normalize already
# appends it there for ip == self_ip; this just stops the loopback line from
# claiming it first.


def derive_domain(hostname: str, append: str = "") -> str:
    """addHost domain derivation. 'BAMacBook' -> 'BAMacBook';
    'a.b' -> 'b'; bare name with append -> append.
    [DERIVE_DOMAIN_NONE_GUARD_V1] A None/empty name has no domain - return the
    append (or "") instead of crashing on .split()."""
    if not hostname:
        return append or ""
    name_part = hostname.split(".", 1)[0]
    domain_part = hostname.split(".", 1)[1] if "." in hostname else name_part
    if domain_part == name_part:
        return append or name_part
    return domain_part


def addhost_lines(host: str, host_path: str, append: str = "") -> list[str]:
    """The two frognet_hosts lines addHost writes for a peer:
        <.1> <domain> FrogNetHost.<domain>
        <.2> FrogNetAdmin.<domain>"""
    domain = derive_domain(host, append)
    admin_ip = host_path.rsplit(".", 1)[0] + ".2"
    return [
        f"{host_path} {domain} FrogNetHost.{domain}",
        f"{admin_ip} FrogNetAdmin.{domain}",
    ]


def reconcile_added(added, prior_names=None, logger=lambda s: None):
    """[HOSTS_AUTHORITATIVE_NAME_V1 / HOSTS_NAME_CHANGE_RUNAGAIN_V1]

    added       = list of (host, host_path, dev, authoritative) the walk recorded.
                  authoritative=True is the name a node returned for ITSELF via
                  echo (or the broker override) - the source of truth.
                  authoritative=False is a relayed vouch name (a neighbor's
                  getHosts entry, which may be the generic "FrogNetHost").
    prior_names = {host_path(.1): domain} parsed from the current /etc/hosts.

    Returns (lines, host_name_changed):
      lines             = the addhost_lines for the CHOSEN name per IP. Per IP an
                          authoritative name wins; a vouch name is a fallback only
                          when no echo named that peer. This is what removes the
                          duplicate "FrogNetHost.FrogNetHost" line for a peer also
                          reached by a direct echo.
      host_name_changed = True iff an authoritative name's domain differs from the
                          domain already in /etc/hosts for that IP (the node
                          changed names; the old name is deprecated). Only an
                          authoritative name can deprecate - a vouch never does.
    """
    auth_name: dict = {}      # host_path(.1) -> authoritative name
    vouch_name: dict = {}     # host_path(.1) -> relayed fallback name
    ip_order: list = []
    for host, host_path, _dev, is_auth in added:
        if host_path not in auth_name and host_path not in vouch_name:
            ip_order.append(host_path)
        if is_auth:
            auth_name[host_path] = host          # last authoritative wins (stable)
        else:
            vouch_name.setdefault(host_path, host)

    lines: list[str] = []
    for host_path in ip_order:
        name = auth_name.get(host_path) or vouch_name.get(host_path)
        # [NAMELESS_HOST_SKIP_V1] An echo-less authoritative entry (host="") with
        # no relayed vouch yields no name at all. A host line with no name is
        # useless and derive_domain(None) crashes, so skip it - reachability is
        # tracked separately; the name fills in once an echo or vouch supplies one.
        if not name:
            continue
        lines += addhost_lines(name, host_path)

    host_name_changed = False
    if prior_names:
        for host_path, name in auth_name.items():
            dom = derive_domain(name)
            prev = prior_names.get(host_path)
            # [BLANK_AUTH_NAME_GUARD_V1] A blank authoritative name carries no
            # information: the line-builder above already fell back to the vouch
            # name, so the real name stays in the file. Flagging host_name_changed
            # on an empty dom is a phantom rename - prev never equals "" so it
            # fires every pass and livelocks runAgain while /etc/hosts is unchanged.
            # Only a NON-EMPTY authoritative name may deprecate a prior name.
            if dom and prev is not None and prev != dom:
                host_name_changed = True
                logger(f"HOSTS_NAME_CHANGE ip={host_path} old={prev} new={dom} "
                       f"reason=authoritative_supersedes_deprecated_name")
    return lines, host_name_changed


def local_lines(eth0_ip: str, domain: str) -> list[str]:
    """mergeHostsAndResolv local_identity: 2-field local lines (no bare name;
    the FrogNetHost alias is appended during staging for the self line)."""
    admin_ip = eth0_ip.rsplit(".", 1)[0] + ".2"
    return [
        f"{eth0_ip} FrogNetHost.{domain}",
        f"{admin_ip} FrogNetAdmin.{domain}",
    ]


def _normalize(line: str, self_ip: str):
    """stage_hosts awk: keep the FrogNetHost./FrogNetAdmin. field; self
    FrogNetHost line gets a trailing 'FrogNetHost'."""
    parts = line.split()
    if not parts or not parts[0].startswith("10."):
        return None
    ip = parts[0]
    keep = ""
    for f in parts[1:]:
        if f.startswith("FrogNetHost.") or f.startswith("FrogNetAdmin."):
            keep = f
            break
    if not keep:
        return None
    if ip == self_ip and keep.startswith("FrogNetHost."):
        return f"{ip} {keep} FrogNetHost"
    return f"{ip} {keep}"


def build_etc_hosts(frognet_hosts_lines: list[str], self_ip: str) -> list[str]:
    """Reproduce stage_hosts output (header + 127 line + sort -u of normalized
    10.x lines). Lexical sort matches coreutils `sort` in C locale."""
    normalized = []
    for ln in frognet_hosts_lines:
        n = _normalize(ln, self_ip)
        if n is not None:
            normalized.append(n)
    block = sorted(set(normalized))   # sort -u (lexical)
    return list(HOSTS_HEADER) + block


def _ip_to_int(ip: str) -> int:
    a, b, c, d = (int(x) for x in ip.split("."))
    return (a << 24) | (b << 16) | (c << 8) | d


def _num(v, default=0.0):
    """[RANK_NUM_GUARD_V1] Coerce one capability field to a number, tolerating a
    malformed publish - a nested object/list/None/garbage where a scalar was
    expected (e.g. mem_available_kb arriving as a dict, which crashed the whole
    merge in select_database_host._rank). Never raises: a bad field degrades that
    one candidate's score, it does not take the merge down. bool is rejected (it
    is an int subclass but never a meaningful perf number here)."""
    if isinstance(v, bool):
        return default
    if isinstance(v, (int, float)):
        return v
    if isinstance(v, str):
        try:
            return float(v)
        except ValueError:
            return default
    return default


import time

_clock = time.time   # [ENVELOPE_TS_V1] injectable for oracles


def _capability_index(role_gate, role="databasehost", dbhost="databasehost_control.frognet"):
    """Read each candidate's capability from the role's own service tuple
    `<role>/capability` (memory, never probes). Returns {ip: capability_dict} for
    hosts that PASS role_gate(cap). role_gate is a predicate, e.g.
    lambda c: c.get('mysql_running'). Empty on any error -> caller degrades."""
    import os as _os
    # [OFFLINE_TUPLES_GATE_V1] Under FROGNET_OFFLINE_TUPLES=1 (set by the install's
    # pre-activation sim gate and any offline test) do NOT reach the network for
    # capability. The oracles/sim run merge over FAKE node IPs; a live read either
    # blocks (routable-but-dead on a mesh box -> the gate hangs) or returns real
    # capability (-> the fixed-expectation /etc/hosts oracles pick a real elected host
    # instead of the deterministic highest-.1 floor and FAIL). Empty here == the
    # degraded floor the tests expect. Production leaves the var unset and reads live.
    if _os.environ.get("FROGNET_OFFLINE_TUPLES") == "1":
        return {}
    out = {}
    try:
        from core import frognet_tuples as T
    except Exception:
        return out
    import time as _time
    # [DBHOST_BALLOT_FRESHNESS_V1] apply the SAME admissibility the service election
    # uses (frognet_role_elect.gather_candidates): a capability tuple with ts==0 or
    # older than FROGNET_BALLOT_MAX_AGE_S is a record of a host that stopped speaking
    # and is INADMISSIBLE. Without this the floor election counted a quiet host's stale
    # tuple that the service election correctly refused, so the two paths disagreed and
    # databasehost.frognet split (e.g. floor picked a stale .1 the service dropped).
    _max_age = int(_os.environ.get("FROGNET_BALLOT_MAX_AGE_S", "1800"))
    try:
        for r in T.get(role, "capability", dbhost=dbhost):
            blob = r.get("value", {}) or {}
            cap = blob.get("capability") or blob
            ip = cap.get("lan_ip") or r.get("addr", "")
            try:
                # [ENVELOPE_TS_V1] the row's age is the STORE's, not the writer's.
                # A payload may carry a ts of its own; it is not considered. Judging
                # a ballot by the publisher's clock meant a node two minutes slow was
                # refused everywhere while publishing correctly.
                _env = r.get("age_s")
                ts = float(_clock() - _env) if _env is not None else 0.0
            except (TypeError, ValueError):
                ts = 0.0
            if ts == 0 or int(_time.time() - ts) > _max_age:
                continue
            o = ip.split(".")
            if len(o) == 4 and ip.startswith("10.") and o[3] == "1" and role_gate(cap):
                cap = dict(cap)
                cap["_perf"] = {"loadavg": blob.get("loadavg") or cap.get("loadavg") or {}}
                out[ip] = cap
    except Exception:
        return {}
    return out


CONTROL_NAME = "databasehost_control.frognet"


def role_barrier_ready(etc_hosts, role="databasehost",
                       dbhost="databasehost_control.frognet", logger=None):
    """[ROLE_BARRIER_PER_ROLE_V1] May THIS role decide yet?

    A role may decide once the control host holds a fresh capability record, FOR THAT
    ROLE, from every live machine. Decide over a partial pool and nodes that merged at
    different moments pick different winners.

    The barrier used to exist only for databasehost, and it gated the whole election
    loop -- so mediahost waited on databasehost capability records, which are not an
    input to the media election in any way. A machine could have published its
    mediahost capability and still hold the media election shut because it had not yet
    published its databasehost one. Now each role waits on its own records and nothing
    else, which is both correct and strictly more permissive: mediahost decides as soon
    as the media information is complete.

    Live machines = the reachable .1 FrogNetHost entries in the converged block (a host
    with no route was already dropped by HOSTS_GATE, so it is not awaited). A lone
    FrogNetHost is trivially ready for every role -- it is the only machine and it
    published its own capability -- so a stand-alone node elects ITSELF for everything.
    This gate controls WHEN a role may agree, never who wins.

    Returns (ready, alive, recorded).
    """
    log = logger or (lambda *_a, **_k: None)
    alive = set()
    for l in etc_hosts:
        p = l.split()
        if (len(p) >= 2 and p[0].endswith(".1")
                and any(t.startswith("FrogNetHost.") for t in p[1:])):
            alive.add(p[0])
    try:
        recorded = set(_capability_index(lambda c: True, role=role,
                                         dbhost=dbhost).keys())
    except Exception:
        recorded = set()
    missing = alive - recorded
    ready = not missing
    if not ready:
        log(f"ROLE_DEFER role={role} missing={sorted(missing)} "
            f"recorded={sorted(recorded)} alive={sorted(alive)} "
            f"-- this role waits for every live machine to publish ITS record")
    return ready, alive, recorded


def databasehost_barrier_ready(etc_hosts, dbhost="databasehost_control.frognet",
                               logger=None):
    """Compatibility wrapper: the databasehost case of role_barrier_ready."""
    return role_barrier_ready(etc_hosts, "databasehost", dbhost=dbhost, logger=logger)


def control_host_ip(etc_hosts: list[str]) -> str:
    """The deterministic control host: highest 10.x.x.1 GATEWAY in this hosts block.
    Control hosts the Services/SD: coordination plane, so it must be a .1 that runs
    the DB API stack - never an off-mesh non-.1 candidate (those can win the DATA role
    but never coordination). Pure function of the visible .1 set, so every node that
    sees the same block computes the same control without an election. '' if none."""
    dot_ones = []
    for line in etc_hosts:
        if not line or line.startswith("#"):
            continue
        ip = line.split()[0]
        o = ip.split(".")
        if len(o) == 4 and ip.startswith("10.") and o[3] == "1":
            # [DBHOST_EXCLUDE_RESERVED_V1] The control host must be a real FrogNetHost
            # .1 -- its own /24 identity -- never a 10.253.x transit or 10.254.x chorus
            # pool address. This is the authoritative coordination host every node
            # computes and the capability election reads FROM, so a corrupted identity
            # in a reserved range here (as Seattle6's 10.254.1.1) poisons the whole
            # election downstream. Same gate discovery applies everywhere.
            if ip.startswith("10.253.") or ip.startswith("10.254."):
                continue
            dot_ones.append(ip)
    return max(dot_ones, key=_ip_to_int) if dot_ones else ""


def set_control_host(etc_hosts: list[str]) -> list[str]:
    """Write the `<highest .1> databasehost_control.frognet` line, replacing any prior
    one. Deterministic and capability-free, so it can be written FIRST each merge -
    the SD: coordination plane (capability tuples, Services) resolves this name, and
    the data-host election reads from it. No-op if there is no .1 in the block."""
    ip = control_host_ip(etc_hosts)
    out = [l for l in etc_hosts if CONTROL_NAME not in l]
    if ip:
        out.append(f"{ip} {CONTROL_NAME}")
    return out


def select_database_host(etc_hosts: list[str], dbhost: str = "databasehost_control.frognet",
                         logger=None) -> list[str]:
    """selectNewDatabaseHost - capability-GATED. Among the .1 hosts, pick the best one
    that ACTUALLY HAS MYSQL (read from the role's own databasehost/capability tuple). DB
    is memory-bound: rank by RAM then cores, highest-IP only as the final tiebreak. NEVER
    elects a host without mysql. Degrades to highest-IP ONLY if no capability data is
    available at all (transient unreachable) - and only among the .1 hosts present.

    [DBHOST_FLOOR_TRACE_V1] Emits exactly which branch decided databasehost.frognet so a
    merge log says WHY - a real mysql pick, no local mysql, or a no-capability degrade
    (NOT mysql-verified) - instead of leaving it to be inferred from the bare result line."""
    _log = logger or (lambda s: print(s, flush=True))
    # the .1 hosts present in this hosts block
    dot_ones = []
    for line in etc_hosts:
        if not line or line.startswith("#"):
            continue
        ip = line.split()[0]
        o = ip.split(".")
        if len(o) == 4 and ip.startswith("10.") and o[3] == "1":
            # [DBHOST_EXCLUDE_RESERVED_V1] A databasehost candidate is a FrogNetHost
            # .1 -- its OWN /24 identity. The 10.253.x (transit /30) and 10.254.x
            # (chorus) pools are NOT node identities; discovery excludes them
            # everywhere. Excluding them here is what makes the highest-.1 baseline
            # below correct: without it a corrupted identity that landed in 10.254.x
            # (as Seattle6's did -> 10.254.1.1) becomes the highest .1 and wins.
            if ip.startswith("10.253.") or ip.startswith("10.254."):
                continue
            dot_ones.append(ip)
    if not dot_ones:
        return list(etc_hosts)

    capable = _capability_index(
        lambda c: bool(c.get("mysql_running", c.get("mysql"))), dbhost=dbhost)
    # intersect: only .1 hosts in THIS block that are mysql-capable AND serving
    eligible = {ip: capable[ip] for ip in dot_ones if ip in capable}

    if eligible:
        import math
        def _rank(ip):
            c = eligible[ip]
            # [RANK_NUM_GUARD_V1] every capability field is read through _num so a
            # malformed publish (a dict/None/garbage where a scalar is expected)
            # degrades this candidate's score instead of crashing the merge.
            cores = max(1, int(_num(c.get("cores", 1), 1)))
            mem_avail_gb = _num(c.get("mem_available_kb"), 0) / (1024 * 1024)
            mem_total_gb = _num(c.get("mem_total_kb"), 0) / (1024 * 1024)
            # [DBHOST_STATIC_RANK_V1] rank on INSTALLED (total) RAM, never AVAILABLE.
            # Available memory is runtime state that changes on every publish, so a
            # node's own capability tuple was not static write-to-write: the cold
            # election picked different winners as free RAM drifted (thrash), and two
            # boxes reading at different instants disagreed at cold start. Installed RAM
            # is fixed capability -> the same box ranks identically every write and all
            # boxes agree. (Honors DBHOST_NO_LOAD_V1: free RAM IS a load signal.) Fall
            # back to available only if a publisher omitted mem_total_kb.
            mem_gb = mem_total_gb if mem_total_gb > 0 else mem_avail_gb
            innodb_gb = _num(c.get("mysql_innodb_pool_bytes"), 0) / (1024 ** 3)
            ram_score = mem_gb * 1.0 + innodb_gb * 0.5
            wmbps = _num(c.get("disk_write_mbps"), 0.0)
            fsync_ms = _num(c.get("disk_fsync_ms"), 0.0)
            if wmbps > 0:
                disk_perf = math.log10(max(1.0, wmbps)) * 12.0
                if fsync_ms > 0:
                    disk_perf *= max(0.3, min(1.0, 5.0 / fsync_ms))
            else:
                klass = (c.get("disk_class") or "unknown").lower()
                disk_perf = 8.0 * {"nvme": 1.6, "ssd": 1.3, "hdd": 1.0,
                                   "sdcard": 0.4, "unknown": 0.9}.get(klass, 0.9)
            disk_free = _num(c.get("disk_free_gb"), 0.0)
            cap_factor = 0.1 if disk_free < 1.0 else 0.5 if disk_free < 5.0 else 1.0
            bench = _num(c.get("cpu_bench_total"), 0.0)
            cpu_score = (bench / 1000.0) if bench > 0 else (cores * 0.5)
            # [DBHOST_NO_LOAD_V1] load is NOT a selection factor - see database_handler.
            score = (ram_score + disk_perf + cpu_score) * cap_factor
            return (score, _ip_to_int(ip))           # IP only as final tiebreak
        # [DBHOST_INCUMBENCY_HOLD_V1] John's routing law (ROUTE_INCUMBENCY_HOLD_V1)
        # applied to the floating DATA host: if the CURRENT databasehost is still
        # eligible (alive + mysql-capable per a fresh tuple), HOLD it - no challenger
        # displaces a healthy incumbent at any score margin. Only re-elect when the
        # incumbent is absent from eligible (gone / dead / no-longer-mysql). Without
        # this, max(_rank) ran every merge over fluctuating mem_available, so the
        # winner oscillated between candidates merge-to-merge (the databasehost flap).
        incumbent = None
        for _l in etc_hosts:
            _p = _l.split()
            if len(_p) >= 2 and _p[1] == "databasehost.frognet":
                incumbent = _p[0]
                break
        held = incumbent if (incumbent and incumbent in eligible) else None
        best_ip = held or max(eligible, key=_rank)
        for ip in sorted(eligible, key=_rank, reverse=True):
            c = eligible[ip]
            _log(f"DBHOST_FLOOR_CAND ip={ip} "
                 f"mysql_running={c.get('mysql_running', c.get('mysql'))} "
                 f"mem_avail_kb={c.get('mem_available_kb')} "
                 f"disk_write_mbps={c.get('disk_write_mbps')} fsync_ms={c.get('disk_fsync_ms')} "
                 f"disk_free_gb={c.get('disk_free_gb')} cpu_bench={c.get('cpu_bench_total')} "
                 f"score={_rank(ip)[0]:.3f}")
        if held:
            _log(f"DBHOST_FLOOR branch=incumbency_hold dot_ones={dot_ones} "
                 f"eligible={list(eligible)} winner={held} "
                 f"reason=healthy_incumbent_held_no_challenger")
        else:
            _log(f"DBHOST_FLOOR branch=mysql_eligible dot_ones={dot_ones} "
                 f"eligible={list(eligible)} winner={best_ip} reason=best_mysql_capable_dot1")
    elif capable:
        # capability data exists but NONE of this block's .1 hosts have mysql:
        # do NOT elect an incapable host - leave any prior line, append nothing new.
        _log(f"DBHOST_FLOOR branch=no_local_mysql dot_ones={dot_ones} "
             f"capable_elsewhere={list(capable)} winner=none "
             f"reason=capability_present_but_no_dot1_here_runs_mysql_elect_nothing")
        return [l for l in etc_hosts if "databasehost.frognet" not in l] + \
               [l for l in etc_hosts if "databasehost.frognet" in l]
    else:
        # [DBHOST_BASELINE_HIGHEST_V1] No specialist capability tuple has published,
        # so no non-baseline machine has claimed the role. Every FrogNetHost .1 runs
        # MySQL and is a databasehost candidate BY DEFINITION, so the baseline winner
        # is simply the highest .1 present. This is not an "unverified" guess -- it is
        # the always-valid default that capability scoring OVERRIDES when a specialist
        # outranks it. dot_ones has already had the reserved chorus/transit ranges
        # excluded at collection, so a pool address (e.g. 10.254.x) can never be the
        # winner here -- which was the actual Seattle6 bug, not this baseline.
        best_ip = max(dot_ones, key=_ip_to_int)
        _log(f"DBHOST_FLOOR branch=baseline_highest_dot1 dot_ones={dot_ones} "
             f"winner={best_ip} reason=no_specialist_capability_every_frognethost_is_a_candidate")

    out = [l for l in etc_hosts if "databasehost.frognet" not in l]
    out.append(f"{best_ip} databasehost.frognet")
    return out


# ---------------------------------------------------------------------------
# [DBHOST_CAPABILITY_ELECTION_V1] Capability-scored databasehost.
#
# select_database_host() above picks the highest 10.x.x.1 - topology deciding who
# serves. This override lets the network decide on MERIT instead: a machine (a .1
# host OR a dropped-in non-.1 DB box that registered a DatabaseCandidate blob)
# wins if its capability memory scores higher. Identity (FrogNetHost = .1) is
# untouched; only the databasehost.frognet ROLE NAME is repointed.
#
# Memory, not messages: this consults TUPLES (System sensor capability +
# DatabaseCandidate blobs) via the transient. It NEVER probes a node. If the
# transient is unreachable or has no capability data, it returns the input
# unchanged - the highest-IP default stands, so a merge can never break on this.
# ---------------------------------------------------------------------------
def select_database_host_by_capability(etc_hosts, dbhost="databasehost_control.frognet"):
    """Override the databasehost line with the best DB host by CAPABILITY. The
    criteria live in the DatabaseRoleHandler; the gather-and-apply mechanics live in
    frognet_role_elect. This function only translates the elected candidate into the
    /etc/hosts line. Falls back to the unchanged list (highest-IP default) on ANY
    error or missing data, so a merge can never break on this.

    Memory, not messages: the election consults capability tuples, never probes."""
    try:
        from core.frognet_role_elect import elect_role
    except Exception:
        return etc_hosts                              # election modules unavailable
    try:
        winner = elect_role("databasehost", dbhost=dbhost)  # registry handler evaluates
        if not winner or not winner.get("lan_ip"):
            return etc_hosts                          # no eligible DB candidate
        ip = winner["lan_ip"]
        out = [l for l in etc_hosts if "databasehost.frognet" not in l]
        out.append(f"{ip} databasehost.frognet")
        return out
    except Exception:
        return etc_hosts                              # transient unreachable -> default stands
