################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""
resolv.py - manageResolv.bash ported. Builds /etc/resolv.conf:
  header / options / search domains / nameserver 127.0.0.1 / upstream (if any) / 8.8.8.8.
  [RESOLV_LOCAL_UPSTREAM_GOOGLE_V1]: nothing else -- no self, no tunnel peers, no LAN neighbours.

WAN nameservers come from exit_host.tsv (written by fixDefaultRoute) if present,
else the fallback heuristic: the non-10.x via of the default route.

NOTE: the oracle log does NOT dump resolv.conf, so this is proven STRUCTURALLY
(correct content for given inputs), not against a logged artifact.
"""
from __future__ import annotations

GOOGLE_DNS = "8.8.8.8"   # [RESOLV_LOCAL_UPSTREAM_GOOGLE_V1] always last


def build_resolv(local_domain: str, hostname: str, upstream: str) -> list[str]:
    """[RESOLV_LOCAL_UPSTREAM_GOOGLE_V1] 127.0.0.1, the upstream (if any), 8.8.8.8 -- nothing else."""
    out = [
        "################################################",
        "# AUTO-GENERATED BY discovery.live (merge tail)",
        "# FrogNet Unified Routing Edition (2025)",
        "# DO NOT EDIT MANUALLY",
        "################################################",
        "",
        "# Section 1: options",
        "options timeout:1 attempts:1",
        "",
        "# Section 2: search domains",
    ]
    if local_domain and hostname:
        out.append(f"search {local_domain} {hostname}")
    out.append("")
    out += ["# Section 3: nameservers", "# Local FrogNet DNS", "nameserver 127.0.0.1", ""]
    if upstream and upstream != GOOGLE_DNS and not upstream.startswith("127."):
        out.append(f"nameserver {upstream}")
    out.append(f"nameserver {GOOGLE_DNS}")
    return out
