################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""
resolv.py - manageResolv.bash ported. Builds /etc/resolv.conf:
  header / options / search domains / nameserver 127.0.0.1 / WAN fallback NS.

WAN nameservers come from exit_host.tsv (written by fixDefaultRoute) if present,
else the fallback heuristic: the non-10.x via of the default route.

NOTE: the oracle log does NOT dump resolv.conf, so this is proven STRUCTURALLY
(correct content for given inputs), not against a logged artifact.
"""
from __future__ import annotations


def build_resolv(local_domain: str, hostname: str, wan_ns: list[str],
                 peer_ns: list[str] | None = None,
                 self_ip: str = "") -> list[str]:
    out = [
        "################################################",
        "# AUTO-GENERATED BY discovery.live (merge tail)",
        "# FrogNet Unified Routing Edition (2025)",
        "# DO NOT EDIT MANUALLY",
        "################################################",
        "",
        "# Section 1: options",
        "options timeout:1 attempts:1",
        "",
        "# Section 2: search domains",
    ]
    if local_domain and hostname:
        out.append(f"search {local_domain} {hostname}")
    out.append("")
    out += ["# Section 3: nameservers", "# Local FrogNet DNS", "nameserver 127.0.0.1"]

    # [SELF_IP_IS_A_RESOLVER_V1] This machine's own .1, immediately under
    # 127.0.0.1.
    #
    # dnsmasq binds 127.0.0.1 AND the node's own address (listen-address=
    # 127.0.0.1,<self .1> in frognet_forwarders_auto.conf), so both answer the
    # same names. They are not interchangeable to a resolver: a query sourced
    # from the loopback and one sourced from the LAN address take different
    # paths through netfilter and different bind sockets, and anything that
    # copies this file to reach us -- or any local client that cannot use
    # loopback -- needs the routable one. Directly under 127.0.0.1 so it is
    # tried before any peer or the WAN gateway.
    if self_ip and not self_ip.startswith("127."):
        out.append(f"nameserver {self_ip}")
    out.append("")

    # [PEER_PRIMARY_IS_A_RESOLVER_V1] The machine at the far end of each tunnel.
    #
    # Each pond's primary knows its own pond's names. Without these a node
    # resolves only what its own pond knows -- ask BABox for
    # brokerhost.seattle5 and it has never heard of it. With them the query
    # falls through to Seattle5's primary, which has. Proven on BABox
    # 2026-08-12: nslookup returned 10.250.250.155 with 10.250.250.1 present
    # and nothing without it.
    #
    # ORDER. 127.0.0.1 first, above, so own-pond and .frognet names never leave
    # the box. Peers next. WAN last. With options timeout:1 attempts:1 an
    # unreachable peer costs a second and falls through rather than stalling.
    #
    # The list comes from the merge, which learned it in the walk: each peer
    # answered on a device and named itself. It is not derived here from the
    # kernel table, because the kernel table cannot answer it -- AllowedIPs is
    # 10.0.0.0/8 on every FrogNet tunnel and names no pond, and an interface's
    # several /24 routes are mostly TRANSIT rather than the pond at the far
    # end. Both measured, 2026-08-12.
    _pseen: set = set()
    peers = [p for p in (peer_ns or [])
             if p and not (p in _pseen or _pseen.add(p))]
    if peers:
        out.append("# Tunnel peer primaries")
        out += [f"nameserver {ip}" for ip in peers]
        out.append("")
    # dedupe WAN NS, stable order
    seen = set()
    uniq = [x for x in wan_ns if x and not (x in seen or seen.add(x))]
    if uniq:
        out.append("# WAN fallback DNS")
        out += [f"nameserver {ip}" for ip in uniq]
    return out


def wan_ns_from_default(kernel) -> list[str]:
    """Fallback heuristic: non-10.x via of default routes."""
    ns = []
    for line in kernel.show_default():
        parts = line.split()
        if "via" in parts:
            via = parts[parts.index("via") + 1]
            if via and not via.startswith("10.") and via.count(".") == 3:
                ns.append(via)
    return ns
