################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""test_resolv_layout_oracle.py - [RESOLV_LOCAL_UPSTREAM_GOOGLE_V1]

John, 2026-09-26: the merge writes /etc/resolv.conf with ONLY 127.0.0.1, the upstream (if any), and 8.8.8.8.
No tunnel peer primaries, no LAN neighbours, not this node's own address, no "# WAN fallback DNS" header.
"The upstream" is the one the merge already gives dnsmasq (dnsmasq_upstream.conf): exit_host.tsv's next hop, else
the default route's gateway, never 127.x -- one definition, live._dns_upstream.

Drives the REAL discovery.live._resolv_text with the merge's own sentinels present -- a tunnel peer
(tunnel_peers.tsv), a LAN neighbour (frognet_neighbor_via) -- and requires the file byte for byte, for a node
with an upstream (default route via 192.168.0.1) and for one with none (no default route).
FAILS on every earlier layout (peers listed; or self listed and no 8.8.8.8); PASSES on this one.
"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

HEAD = """################################################
# AUTO-GENERATED BY discovery.live (merge tail)
# FrogNet Unified Routing Edition (2025)
# DO NOT EDIT MANUALLY
################################################

# Section 1: options
options timeout:1 attempts:1

# Section 2: search domains
search Seattle5 FrogNetHost.Seattle5

# Section 3: nameservers
# Local FrogNet DNS
nameserver 127.0.0.1

"""
WANT_UP = HEAD + "nameserver 192.168.0.1\nnameserver 8.8.8.8\n"
WANT_NONE = HEAD + "nameserver 8.8.8.8\n"


class K:
    def __init__(self, gw):
        self.gw = gw

    def show_default(self):
        return [f"default via {self.gw} dev wlan0 metric 601", f"default via {self.gw} dev wlan1 metric 602"] if self.gw else []


def main():
    d = tempfile.mkdtemp()
    os.environ["FROGNET_SENTINEL_DIR"] = d
    open(os.path.join(d, "tunnel_peers.tsv"), "w").write("wg0\t10.155.155.1\nwg1\t10.123.123.1\nwg2\t10.251.251.1\n")
    open(os.path.join(d, "frognet_neighbor_via"), "w").write(
        "# <their DHCP lease on our segment> <their FrogNet .1>\n10.250.250.221 10.188.188.1\n")
    from discovery import live
    ok = True
    for label, gw, want in (("with an upstream", "192.168.0.1", WANT_UP), ("with no upstream", "", WANT_NONE)):
        k = K(gw)
        if hasattr(live, "_default_gateway"):          # the real kernel lookup, answered from this fixture
            live._default_gateway = lambda _k, _gw=gw: _gw
        got = live._resolv_text(k, "FrogNetHost.Seattle5",
                                "Seattle5")
        ns = [l.split()[1] for l in got.splitlines() if l.startswith("nameserver ")]
        this = got == want
        ok = ok and this
        print(f"  [{'PASS' if this else 'FAIL'}] {label}: exactly 127.0.0.1, upstream (if any), 8.8.8.8 (written: {ns})")
        if not this:
            import difflib
            print("".join(difflib.unified_diff(want.splitlines(True), got.splitlines(True), "want", "got")))
    print("ALL RESOLV-LAYOUT ORACLE CHECKPOINTS PASS" if ok else "RESOLV-LAYOUT ORACLE FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
