################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""
test_hosts_oracle.py - full-merge proof. Runs orchestrate.merge over the NY-1
oracle topology and asserts BOTH provable artifacts match the log verbatim:
  - final route table == oracle final `ip r` (10.x rows)
  - /etc/hosts == oracle /etc/hosts (header + 8 host pairs + databasehost line)
"""
import os as _os  # [OFFLINE_TUPLES_GATE_V1] build-oracle floors deterministically:
_os.environ.setdefault("FROGNET_OFFLINE_TUPLES", "1")  # never read live capability
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from discovery.sim.topology import build_ny1
from discovery.orchestrate import merge
from discovery.test_kernel_oracle import ORACLE_FINAL_IPR_REAPED, _diff

# Daemon bringup registered the 3 DIRECT-channel peers (BRINGUP_HOSTS_REGISTER).
# [HOSTS_NEED_ROUTE_V1] BABox's wg0 is DEAD, so its /24 is reaped and it has NO
# route - it is therefore GATED OUT of /etc/hosts (a name without a route is a
# hint, not an entry). Seattle5/BAMacBook stay: their /24s route.
BRINGUP_PEERS = [
    ("BABox", "10.111.11.1"),
    ("BAMacBook", "10.179.179.1"),
    ("Seattle5", "10.250.250.1"),
]

# Oracle /etc/hosts, verbatim.
ORACLE_ETC_HOSTS = [
    "################################################",
    "# AUTO-GENERATED BY mergeHostsAndResolv.bash   #",
    "################################################",
    # [FROGNETHOST_IS_NOT_LOOPBACK_V1] The bare alias moved OFF this line onto
    # the self line below, which holds the real address. With it here the
    # loopback sorted first, resolvers took the first match, and the bare name
    # resolved to 127.0.0.1 - so a peer aiming at "FrogNetHost" reached itself.
    # Shared fixture: test_runmerge_oracle and test_fabric_integration import
    # ORACLE_ETC_HOSTS from here, so all three move together.
    "127.0.0.1 localhost",
    "10.102.60.1 FrogNetHost.New-York-1 FrogNetHost",
    "10.102.60.2 FrogNetAdmin.New-York-1",
    "10.120.120.1 FrogNetHost.Seattle2",
    "10.120.120.2 FrogNetAdmin.Seattle2",
    "10.130.130.1 FrogNetHost.Seattle3",
    "10.130.130.2 FrogNetAdmin.Seattle3",
    "10.160.160.1 FrogNetHost.Seattle6",
    "10.160.160.2 FrogNetAdmin.Seattle6",
    "10.179.179.1 FrogNetHost.BAMacBook",
    "10.179.179.2 FrogNetAdmin.BAMacBook",
    "10.250.250.1 FrogNetHost.Seattle5",
    "10.250.250.2 FrogNetAdmin.Seattle5",
    "10.28.28.1 FrogNetHost.New-York-2",
    "10.28.28.2 FrogNetAdmin.New-York-2",
    "10.250.250.1 databasehost.frognet",
    "10.250.250.1 databasehost_control.frognet",
]


def main():
    ok = True
    disc, k, seeds, upstream = build_ny1()
    out = merge(disc, k, seeds, upstream,
                local=("10.102.60.1", "New-York-1"),
                bringup_peers=BRINGUP_PEERS)

    ok &= _diff("final ip r", out["final_table"], ORACLE_FINAL_IPR_REAPED)
    ok &= _diff("/etc/hosts", out["etc_hosts"], ORACLE_ETC_HOSTS)

    # [HOSTS_NEED_ROUTE_V1] Name the rule explicitly so it can't be silently
    # re-broken by re-adding a line to the verbatim table above: a peer with NO
    # route is gated OUT, a routed peer is IN.
    hosts_blob = "\n".join(out["etc_hosts"])
    gate_ok = ("BABox" not in hosts_blob) and ("FrogNetHost.Seattle2" in hosts_blob)
    print(("  PASS " if gate_ok else "  FAIL ")
          + "HOSTS_NEED_ROUTE: dead-wg0 BABox gated out, routed Seattle2 kept")
    ok &= gate_ok

    # [HOSTS_SINGLE_WRITER_V1 / HOSTS_DEDUP_V1] frognet_hosts is now written by
    # exactly one route-gated author (the merge). Prove the sentinel ITSELF (not
    # just the derived /etc/hosts) obeys the route table and carries no
    # duplicates - the two properties that were broken on the box, where the
    # tunnel daemon appended every brought-up channel (reachable or not) with
    # the addHostAndPropogate dedup record disabled.
    fh = out["frognet_hosts"]

    # (1) no duplicate lines
    nodup_ok = len(fh) == len(set(fh))
    if not nodup_ok:
        from collections import Counter
        dups = [l for l, c in Counter(fh).items() if c > 1]
        print(f"  FAIL HOSTS_DEDUP: duplicate frognet_hosts lines: {dups}")
    else:
        print("  PASS HOSTS_DEDUP: frognet_hosts has no duplicate lines")
    ok &= nodup_ok

    # (2) every 10.x peer line's /24 is an installed winner (or our own subnet).
    # This is the invariant: a name in frognet_hosts implies a route to it.
    routable = {row.split()[0].rsplit("/", 1)[0].rsplit(".", 1)[0]
                for row in out["final_table"]
                if row.split() and row.split()[0].endswith("/24")}
    self_pref = "10.102.60"   # New-York-1 eth0 (this oracle's local node)
    offenders = []
    for ln in fh:
        f = ln.split()
        if not f or not f[0].startswith("10."):
            continue
        pref = f[0].rsplit(".", 1)[0]
        if pref != self_pref and pref not in routable:
            offenders.append(ln)
    gated_ok = not offenders
    if not gated_ok:
        print("  FAIL HOSTS_NEED_ROUTE(frognet_hosts): non-routable lines: "
              + repr(offenders))
    else:
        print("  PASS HOSTS_NEED_ROUTE(frognet_hosts): "
              "every peer /24 is a routed winner")
    ok &= gated_ok

    print()
    print("ALL HOSTS ORACLE CHECKPOINTS PASS" if ok else "HOSTS ORACLE PROOF FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
