#!/usr/bin/env python3
"""Generate cmdtable.hpp from redis src/commands/*.json (7.2.11).
Only what COMMAND INFO/COUNT/LIST/GETKEYS and arity checks need."""
import json,glob,os,sys
root=sys.argv[1]; out=sys.argv[2]
rows=[]
for f in sorted(glob.glob(os.path.join(root,'src/commands/*.json'))):
    for name,spec in json.load(open(f)).items():
        cont=spec.get('container','')
        ks=spec.get('key_specs',[])
        first=last=step=0; movable=0
        if ks:
            k=ks[0]
            bs=k.get('begin_search',{}); fk=k.get('find_keys',{})
            if 'index' in bs and 'range' in fk:
                first=bs['index']['pos']; r=fk['range']
                last=r['lastkey']; step=r['step']
                if last==-1: last=-1
                elif r.get('limit',0)!=0: movable=1
                else: last=first+last if last>=0 else last
            else: movable=1
            if len(ks)>1: movable=1
        flags=[x.lower() for x in spec.get('command_flags',[])]
        if movable: flags.append('movablekeys')
        cats=['@'+x.lower() for x in spec.get('acl_categories',[])]
        rows.append((cont.lower(),name.lower(),spec['arity'],' '.join(flags),' '.join(cats),first,last,step,spec.get('group',''),spec.get('summary','').replace('"','\\"')[:120]))
def cs(s): return '"'+s.replace('\\','\\\\').replace('"','\\"')+'"'
with open(out,'w') as fp:
    fp.write('// generated by tools/gen_cmdtable.py from redis 7.2.11 src/commands/*.json -- do not edit\n#pragma once\nstruct CmdSpec { const char* container; const char* name; int arity; const char* flags; const char* acl; int first; int last; int step; const char* group; const char* summary; };\nstatic const CmdSpec CMD_TABLE[] = {\n')
    for r in rows:
        fp.write('  {%s,%s,%d,%s,%s,%d,%d,%d,%s,%s},\n'%(cs(r[0]),cs(r[1]),r[2],cs(r[3]),cs(r[4]),r[5],r[6],r[7],cs(r[8]),cs(r[9])))
    fp.write('};\nstatic const int CMD_TABLE_N = %d;\n'%len(rows))
print(len(rows))
