#!/usr/bin/env python3
################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
"""
oracle_forwarders.py — prove discovery/live.py:_write_forwarders reproduces
mergeHostsAndResolv.bash stage_dnsmasq byte for byte.

Method: feed the SAME host table to both.
  - bash side: the actual awk from mergeHostsAndResolv.bash lines 208-218,
    piped through `sort -u`, with the same header and the same two listen
    lines appended, exactly as the script does it.
  - python side: _write_forwarders() imported from the patched live.py.
Then diff the bytes.

Fails on the pre-patch tree (no _write_forwarders) and passes on the patched
tree, which is the point.
"""
import subprocess, sys, os, tempfile, importlib.util

SRC = "/opt/frognet_semantic/discovery/live.py"
BASH = "/usr/local/bin/mergeHostsAndResolv.bash"

# Representative host tables, including the awkward cases:
#   - self line with the trailing bare FrogNetHost alias
#   - a FrogNetAdmin line (must NOT produce a forwarder)
#   - unsorted input (sort -u must normalize)
#   - a non-10. line and the 127 line (must be ignored)
CASES = {
    "seattle5_with_seattle2": [
        "################################################",
        "# AUTO-GENERATED BY mergeHostsAndResolv.bash   #",
        "################################################",
        "127.0.0.1 localhost FrogNetHost",
        "10.120.120.1 FrogNetHost.Seattle2",
        "10.102.50.1 FrogNetHost.Seattle5 FrogNetHost",
        "10.102.50.2 FrogNetAdmin.Seattle5",
    ],
    "unsorted_multi": [
        "127.0.0.1 localhost FrogNetHost",
        "10.102.60.1 FrogNetHost.NY1",
        "10.101.10.1 FrogNetHost.BlackBox",
        "10.102.30.1 FrogNetHost.Seattle3 FrogNetHost",
        "10.101.210.1 FrogNetHost.TealBox",
        "10.101.210.2 FrogNetAdmin.TealBox",
    ],
    "single_self_only": [
        "127.0.0.1 localhost FrogNetHost",
        "10.102.50.1 FrogNetHost.Seattle5 FrogNetHost",
    ],
}


def bash_side(lines, self_ip):
    """Run the real awk out of mergeHostsAndResolv.bash against the table."""
    src = open(BASH).read()
    start = src.index('  $AWK \'\n    $1 ~ /^10\\./ {\n      for(i=2;i<=NF;i++){')
    end = src.index("' \"$HOSTS_OUT\" | $SORT -u", start)
    awk_prog = src[start + len("  $AWK '"):end]

    with tempfile.NamedTemporaryFile("w", suffix=".hosts", delete=False) as f:
        f.write("\n".join(lines) + "\n")
        hosts_out = f.name
    try:
        r = subprocess.run(["awk", awk_prog, hosts_out],
                           capture_output=True, text=True, check=True)
        sorted_out = subprocess.run(["sort", "-u"], input=r.stdout,
                                    capture_output=True, text=True, check=True)
    finally:
        os.unlink(hosts_out)

    body = "# AUTO-GENERATED\n" + sorted_out.stdout
    if self_ip:
        body += f"listen-address=127.0.0.1,{self_ip}\nbind-interfaces\n"
    return body


def python_side(lines, tmpdir):
    # live.py is a package module (relative imports); load it as
    # discovery.live with the real package root on sys.path.
    root = "/opt/frognet_semantic"
    if root not in sys.path:
        sys.path.insert(0, root)
    for stale in [m for m in sys.modules if m.startswith("discovery")]:
        del sys.modules[stale]
    import importlib
    mod = importlib.import_module("discovery.live")
    if not hasattr(mod, "_write_forwarders"):
        raise SystemExit("FAIL: live.py has no _write_forwarders — stage_dnsmasq "
                         "is not ported. This is the pre-patch tree.")

    out_path = os.path.join(tmpdir, "etc/dnsmasq.d/frognet_forwarders_auto.conf")
    real = mod._write_if_changed

    def redirected(path, content, logger=print):
        if path.startswith("/etc/dnsmasq.d/"):
            path = os.path.join(tmpdir, path.lstrip("/"))
        return real(path, content, logger)

    mod._write_if_changed = redirected
    changed = mod._write_forwarders(lines, logger=lambda *a: None)
    return open(out_path).read(), changed, mod, redirected, out_path


def main():
    failures = 0
    for name, lines in CASES.items():
        self_ip = ""
        for ln in lines:
            p = ln.split()
            if len(p) >= 3 and p[0].startswith("10.") and p[2] == "FrogNetHost":
                self_ip = p[0]
        with tempfile.TemporaryDirectory() as td:
            want = bash_side(lines, self_ip)
            got, changed, mod, redirected, out_path = python_side(lines, td)
            if got != want:
                failures += 1
                print(f"  FAIL {name}")
                print("    bash produced:"); print("      " + repr(want))
                print("    python produced:"); print("      " + repr(got))
            else:
                print(f"  ok: {name} ({len(want.splitlines())} lines, identical)")
                if not changed:
                    failures += 1
                    print(f"  FAIL {name}: first write returned changed=False")
                # idempotence: second write of the same content must be a no-op
                mod._write_if_changed = redirected
                if mod._write_forwarders(lines, logger=lambda *a: None):
                    failures += 1
                    print(f"  FAIL {name}: rewriting identical content reported changed")

    # An empty / header-only table must not blow away the file.
    with tempfile.TemporaryDirectory() as td:
        _, _, mod, redirected, _ = python_side(CASES["single_self_only"], td)
        mod._write_if_changed = redirected
        if mod._write_forwarders(["127.0.0.1 localhost FrogNetHost"],
                                 logger=lambda *a: None):
            failures += 1
            print("  FAIL empty table reported a change")
        else:
            print("  ok: table with no FrogNetHost lines writes nothing")

    print("RESULT: " + ("PASS" if failures == 0 else f"FAIL ({failures})"))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
