#!/bin/bash
################################################################
#  Copyright (C) 2016-2026 Fawcett Innovations LLC             #
#                                                              #
#  SPDX-License-Identifier: GPL-2.0-only                       #
#                                                              #
#  This program is free software; you can redistribute it      #
#  and/or modify it under the terms of the GNU General Public  #
#  License as published by the Free Software Foundation;       #
#  version 2 of the License, and no other version.             #
#                                                              #
#  This program is distributed in the hope that it will be     #
#  useful, but WITHOUT ANY WARRANTY; without even the implied  #
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
#  PURPOSE.  See the GNU General Public License for details.   #
#                                                              #
#  See COPYRIGHT and LICENSE at the root of this tree.         #
################################################################
##############################################################
# frognet_setup_v4_helper.bash
#
# v4-specific operations for setup_frognet.html.  Companion to
# frognet_setup_helper.bash (which handles identity/wifi/state).
#
# All subcommands emit a single JSON object on stdout.
# Errors emit {"ok":false,"error":"..."} and exit 0 so PHP can pass
# the body through to the browser unchanged.
#
# Subcommands:
#   broker_state                                — read current pond.conf
#   apply_broker <host> <port> <pond> <pw> <chorus_csv>
#                                               — write pond.conf
#   clear_broker                                — remove pond.conf
#   register <pubkey>                           — POST to broker /register
#   reboot                                      — schedule a reboot
#   qr <url>                                    — emit base64 PNG of url
#
# Requires: jq, curl, qrencode (Debian: apt install qrencode).
# PHP runs this via sudo; sudoers must permit it.
##############################################################

set -o pipefail

POND_CONF="${FROGNET_POND_CONF:-/etc/frognet/pond.conf}"
GATEWAYS_CONF="${FROGNET_GATEWAYS_CONF:-/etc/frognet/gateways.conf}"
HOSTAPD_CONF="${FROGNET_HOSTAPD_CONF:-/etc/hostapd/hostapd.conf}"
WG_PRIV="${FROGNET_WG_PRIV:-/etc/frognet/wg.key}"
WG_PUB="${FROGNET_WG_PUB:-/etc/frognet/wg.pub}"

emit()  { jq -nc "$1"; }
fail()  { jq -nc --arg e "$1" '{ok:false,error:$e}'; exit 0; }

# ---------------------------------------------------------------------
# broker_state — read /etc/frognet/pond.conf into JSON
# ---------------------------------------------------------------------
cmd_broker_state() {
    local enabled=false host="" port="" pond="" has_pw=false choruses=""
    if [[ -f "$POND_CONF" ]]; then
        enabled=true
        # shellcheck disable=SC1090
        source "$POND_CONF" 2>/dev/null || true
        # The conf file uses BROKER_URL=<host>:<port>; split it.
        if [[ -n "${BROKER_URL:-}" ]]; then
            local u="${BROKER_URL#http://}"; u="${u#https://}"; u="${u%/*}"
            host="${u%:*}"
            port="${u##*:}"
            [[ "$port" == "$host" ]] && port=""
        fi
        pond="${POND_NAME:-}"
        choruses="${CHORUSES:-}"
        [[ -n "${POND_PASSWORD:-}" ]] && has_pw=true
    fi
    jq -nc \
        --argjson enabled "$enabled" \
        --arg host "$host" --arg port "$port" \
        --arg pond "$pond" --arg choruses "$choruses" \
        --argjson has_pw "$has_pw" \
        '{ok:true,enabled:$enabled,host:$host,port:$port,
          pond:$pond,pond_password_set:$has_pw,
          choruses:($choruses|split(" ")|map(select(.!="")))}'
}

# ---------------------------------------------------------------------
# apply_broker <host> <port> <pond> <pond_password> <chorus_csv>
# ---------------------------------------------------------------------
cmd_apply_broker() {
    local host="${1:-}" port="${2:-}" pond="${3:-}" pw="${4:-}" csv="${5:-}"
    [[ -z "$host" || -z "$pond" ]] && fail "host and pond are required"
    [[ -z "$port" ]] && port=18257

    # Whitespace-separated chorus list, csv input.
    local choruses=""
    if [[ -n "$csv" ]]; then
        choruses="$(echo "$csv" | tr ',' ' ' | xargs)"
    fi

    mkdir -p "$(dirname "$POND_CONF")"
    {
        echo "# /etc/frognet/pond.conf"
        echo "# Generated by setup_frognet.html on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "BROKER_URL=https://${host}:${port}"
        echo "POND_NAME=${pond}"
        if [[ -n "$pw" ]]; then
            echo "POND_PASSWORD=${pw}"
        fi
        echo "CHORUSES=\"${choruses}\""
    } > "$POND_CONF"
    chmod 600 "$POND_CONF"

    jq -nc --arg host "$host" --arg port "$port" --arg pond "$pond" \
           --arg choruses "$choruses" \
        '{ok:true,wrote:"'"$POND_CONF"'",
          broker_url:("https://"+$host+":"+$port),
          pond:$pond,choruses:($choruses|split(" ")|map(select(.!="")))}'
}

# ---------------------------------------------------------------------
# clear_broker — remove pond.conf (user unchecked the broker box)
# ---------------------------------------------------------------------
cmd_clear_broker() {
    if [[ -f "$POND_CONF" ]]; then
        rm -f "$POND_CONF"
        jq -nc '{ok:true,cleared:true}'
    else
        jq -nc '{ok:true,cleared:false,note:"already absent"}'
    fi
}

# ---------------------------------------------------------------------
# register <pubkey>  (called by the registration script, optional from UI)
# Reads pond.conf, posts to broker /api/v1/register.  We don't generate
# the keypair here — that's done by the lillypad register flow.
# ---------------------------------------------------------------------
cmd_register() {
    local pubkey="${1:-}"
    [[ -z "$pubkey" ]] && fail "pubkey required"
    [[ ! -f "$POND_CONF" ]] && fail "pond.conf not found — run apply_broker first"

    # shellcheck disable=SC1090
    source "$POND_CONF"
    : "${BROKER_URL:?BROKER_URL missing}" "${POND_NAME:?POND_NAME missing}"

    local hostname subnet
    hostname="$(hostname)"
    if [[ -f "$GATEWAYS_CONF" ]]; then
        # shellcheck disable=SC1090
        source "$GATEWAYS_CONF"
        # GATEWAY_IP is x.y.z.1 — strip last octet, append /24
        subnet="${GATEWAY_IP%.*}.0/24"
    else
        subnet="10.1.1.0/24"
    fi

    local body resp code
    body=$(jq -nc \
        --arg pond "$POND_NAME" --arg pubkey "$pubkey" \
        --arg subnet "$subnet" --arg name "$hostname" \
        --arg pw "${POND_PASSWORD:-}" \
        '{pond:$pond,pubkey:$pubkey,subnet:$subnet,
          node_name:$name,pond_password:$pw}')
    resp=$(curl -sk -w "\n%{http_code}" -X POST \
        -H "Content-Type: application/json" -d "$body" \
        "${BROKER_URL}/api/v1/register" 2>&1)
    code="${resp##*$'\n'}"
    body="${resp%$'\n'*}"
    if [[ "$code" =~ ^2 ]]; then
        jq -nc --argjson r "$body" '{ok:true,registered:$r}'
    else
        jq -nc --arg c "$code" --arg b "$body" \
            '{ok:false,error:("broker returned "+$c+": "+$b)}'
    fi
}

# ---------------------------------------------------------------------
# reboot — fire a delayed reboot so PHP can return first
# ---------------------------------------------------------------------
cmd_reboot() {
    ( sleep 3 && systemctl reboot ) >/dev/null 2>&1 &
    disown
    jq -nc '{ok:true,reboot_in_seconds:3}'
}

# ---------------------------------------------------------------------
# qr <text>  — base64-encoded PNG of the text encoded as a QR code.
# Used to show "scan this to come back after reboot" in the UI.
# ---------------------------------------------------------------------
cmd_qr() {
    local text="${1:-}"
    [[ -z "$text" ]] && fail "text required"
    command -v qrencode >/dev/null 2>&1 || fail "qrencode not installed"
    local png_b64
    png_b64="$(qrencode -o - -s 6 -m 2 "$text" 2>/dev/null | base64 -w0)"
    [[ -z "$png_b64" ]] && fail "qrencode produced no output"
    jq -nc --arg b64 "$png_b64" --arg text "$text" \
        '{ok:true,text:$text,png_base64:$b64}'
}

# ---------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------
sub="${1:-}"; shift || true
case "$sub" in
    broker_state)  cmd_broker_state "$@" ;;
    apply_broker)  cmd_apply_broker "$@" ;;
    clear_broker)  cmd_clear_broker "$@" ;;
    register)      cmd_register     "$@" ;;
    reboot)        cmd_reboot       "$@" ;;
    qr)            cmd_qr           "$@" ;;
    *)             fail "unknown subcommand: $sub" ;;
esac
