#!/usr/bin/env python3
"""Generate include/pyuni_tables.hpp: the code points Python's int() treats as whitespace (str.isspace) and as
decimal digits (unicodedata.decimal), from the running interpreter's Unicode database. int(s) maps each whitespace
code point to ' ' and each decimal digit to its ASCII digit before parsing (_PyUnicode_TransformDecimalAndSpaceToASCII).
usage: gen_pyuni_tables.py > include/pyuni_tables.hpp"""
import sys, unicodedata

space = [c for c in range(0x110000) if chr(c).isspace()]
runs = []   # (first code point, count) where first has decimal value 0 and the run counts up 0..count-1
c = 0
while c < 0x110000:
    if unicodedata.decimal(chr(c), None) == 0:
        n = 1
        while c + n < 0x110000 and unicodedata.decimal(chr(c + n), None) == n: n += 1
        runs.append((c, n)); c += n
    else:
        assert unicodedata.decimal(chr(c), None) is None or c < 0, hex(c)
        c += 1
covered = {s + k for s, n in runs for k in range(n)}
assert covered == {c for c in range(0x110000) if unicodedata.decimal(chr(c), None) is not None}
print('// Generated by tests/gen_pyuni_tables.py from Python %s, Unicode %s. Do not edit.' %
      (sys.version.split()[0], unicodedata.unidata_version))
print('#pragma once')
print('#include <cstdint>')
print('namespace pyuni {')
print('constexpr uint32_t SPACE[] = {')
line = '   '
for c in space:
    item = ' 0x%x,' % c
    if len(line) + len(item) > 118: print(line); line = '   '
    line += item
print(line)
print('};')
print('struct DigitRun { uint32_t first; uint8_t count; };')
print('constexpr DigitRun DIGITS[] = {')
line = '   '
for s, n in runs:
    item = ' {0x%x, %d},' % (s, n)
    if len(line) + len(item) > 118: print(line); line = '   '
    line += item
print(line)
print('};')
print('}  // namespace pyuni')
