#!/usr/bin/env python3
# Generates include/pyuni_s3_tables.hpp from THIS Python's Unicode database (the oracle's, 3.12.3): the character
# behaviour the S3 template code depends on. Regenerate with the Python the oracle runs; the header records its version.
import re, sys, unicodedata
MAX = 0x110000
lower = [(c, [ord(x) for x in chr(c).lower()]) for c in range(MAX) if chr(c).lower() != chr(c)]
assert max(len(v) for _, v in lower) <= 3
upper = [(c, [ord(x) for x in chr(c).upper()]) for c in range(MAX) if chr(c).upper() != chr(c)]
assert max(len(v) for _, v in upper) <= 3
def ranges(pred):
    out, start = [], None
    for c in range(MAX + 1):
        ok = c < MAX and pred(c)
        if ok and start is None: start = c
        if not ok and start is not None: out.append((start, c - 1)); start = None
    return out
alnum = ranges(lambda c: chr(c).isalnum())
upper_az = [(c, chr(c).upper()) for c in range(MAX) if chr(c).upper() and all('A' <= x <= 'Z' for x in chr(c).upper())]
icase = [c for c in range(MAX) if re.fullmatch('[a-z0-9]', chr(c), re.IGNORECASE)]
o = ['// GENERATED by tests/gen_pyuni_s3.py from Python %s, unicodedata %s. Do not edit.' % (sys.version.split()[0], unicodedata.unidata_version),
     '#pragma once', '#include <cstdint>', 'namespace pyuni_s3 {',
     'struct Lower { uint32_t cp; uint8_t n; uint32_t to[3]; };',
     'constexpr Lower LOWER[] = {']
o += ['  {0x%X,%d,{%s}},' % (c, len(v), ','.join('0x%X' % x for x in v + [0] * (3 - len(v)))) for c, v in lower]
o += ['};', 'constexpr Lower UPPER[] = {']
o += ['  {0x%X,%d,{%s}},' % (c, len(v), ','.join('0x%X' % x for x in v + [0] * (3 - len(v)))) for c, v in upper]
o += ['};', 'struct Range { uint32_t lo, hi; };', 'constexpr Range ALNUM[] = {']
o += ['  {0x%X,0x%X},' % r for r in alnum]
printable = ranges(lambda c: chr(c).isprintable())
o += ['};', 'constexpr Range PRINTABLE[] = {   // str.isprintable(), for repr()']
o += ['  {0x%X,0x%X},' % r for r in printable]
o += ['};', 'struct UpperAZ { uint32_t cp; const char* to; };', 'constexpr UpperAZ UPPER_AZ[] = {']
o += ['  {0x%X,"%s"},' % (c, u) for c, u in upper_az]
o += ['};', 'constexpr uint32_t ICASE_AZ09[] = {']
o += ['  ' + ','.join('0x%X' % c for c in icase[i:i + 16]) + ',' for i in range(0, len(icase), 16)]
o += ['};', '}  // namespace pyuni_s3', '']
open('include/pyuni_s3_tables.hpp', 'w').write('\n'.join(o))
print('upper %d, lower %d, alnum ranges %d, upper->A-Z %d, icase [a-z0-9] %d' % (len(upper), len(lower), len(alnum), len(upper_az), len(icase)))
print('icase extras:', [hex(c) for c in icase if c > 127])
