/***************************************************************
 *  Copyright (C) 2016-2026 Fawcett Innovations LLC            *
 *                                                             *
 *  SPDX-License-Identifier: GPL-2.0-only                      *
 *                                                             *
 *  This program is free software; you can redistribute it     *
 *  and/or modify it under the terms of the GNU General Public *
 *  License as published by the Free Software Foundation;      *
 *  version 2 of the License, and no other version.            *
 *                                                             *
 *  This program is distributed in the hope that it will be    *
 *  useful, but WITHOUT ANY WARRANTY; without even the implied *
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    *
 *  PURPOSE.  See the GNU General Public License for details.  *
 *                                                             *
 *  See COPYRIGHT and LICENSE at the root of this tree.        *
 **************************************************************/
// Generated by tools/gen_pyuni_tables.py from Python 3.12.3, Unicode 15.0.0. Do not edit.
#pragma once
#include <cstdint>
namespace pyuni {
constexpr uint32_t SPACE[] = {
    0x9, 0xa, 0xb, 0xc, 0xd, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x85, 0xa0, 0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004,
    0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f, 0x205f, 0x3000,
};
struct DigitRun { uint32_t first; uint8_t count; };
constexpr DigitRun DIGITS[] = {
    {0x30, 10}, {0x660, 10}, {0x6f0, 10}, {0x7c0, 10}, {0x966, 10}, {0x9e6, 10}, {0xa66, 10}, {0xae6, 10},
    {0xb66, 10}, {0xbe6, 10}, {0xc66, 10}, {0xce6, 10}, {0xd66, 10}, {0xde6, 10}, {0xe50, 10}, {0xed0, 10},
    {0xf20, 10}, {0x1040, 10}, {0x1090, 10}, {0x17e0, 10}, {0x1810, 10}, {0x1946, 10}, {0x19d0, 10}, {0x1a80, 10},
    {0x1a90, 10}, {0x1b50, 10}, {0x1bb0, 10}, {0x1c40, 10}, {0x1c50, 10}, {0xa620, 10}, {0xa8d0, 10}, {0xa900, 10},
    {0xa9d0, 10}, {0xa9f0, 10}, {0xaa50, 10}, {0xabf0, 10}, {0xff10, 10}, {0x104a0, 10}, {0x10d30, 10}, {0x11066, 10},
    {0x110f0, 10}, {0x11136, 10}, {0x111d0, 10}, {0x112f0, 10}, {0x11450, 10}, {0x114d0, 10}, {0x11650, 10},
    {0x116c0, 10}, {0x11730, 10}, {0x118e0, 10}, {0x11950, 10}, {0x11c50, 10}, {0x11d50, 10}, {0x11da0, 10},
    {0x11f50, 10}, {0x16a60, 10}, {0x16ac0, 10}, {0x16b50, 10}, {0x1d7ce, 10}, {0x1d7d8, 10}, {0x1d7e2, 10},
    {0x1d7ec, 10}, {0x1d7f6, 10}, {0x1e140, 10}, {0x1e2f0, 10}, {0x1e4f0, 10}, {0x1e950, 10}, {0x1fbf0, 10},
};
}  // namespace pyuni
